/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CreateEntityRouteImport } from './routes/createEntity'
import { Route as IndexRouteImport } from './routes/index'

const CreateEntityRoute = CreateEntityRouteImport.update({
  id: '/createEntity',
  path: '/createEntity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/createEntity': typeof CreateEntityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/createEntity': typeof CreateEntityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/createEntity': typeof CreateEntityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/createEntity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/createEntity'
  id: '__root__' | '/' | '/createEntity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateEntityRoute: typeof CreateEntityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/createEntity': {
      id: '/createEntity'
      path: '/createEntity'
      fullPath: '/createEntity'
      preLoaderRoute: typeof CreateEntityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateEntityRoute: CreateEntityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
